name: Build and push images

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: 127.0.0.1:4000 # temporary override for local registry reachability
  PODMAN_URL: unix:///var/run/docker.sock
  REGISTRY_OWNER: ${{ vars.REGISTRY_OWNER }} # example: my-org or my-user
  TAG: ${{ gitea.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: local/openclaw-hacked-setup
            context: infra/images/ai/assistants/openclaw
            dockerfile: Dockerfile.openclaw

    steps:
      - uses: actions/checkout@v4
        with:
          github-server-url: http://10.90.0.10:3000

      - name: Install podman client
        run: |
          apt-get update
          apt-get install -y podman
          podman --url "${{ env.PODMAN_URL }}" --version

      - name: Test connections
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.REGISTRY_OWNER }}/${{ matrix.image.name }}
        run: |
          ls -l /var/run/docker.sock || true
          podman --url "${{ env.PODMAN_URL }}" info | sed -n '/idMappings/,+12p' || true
          getent hosts host.containers.internal || true

          echo "Testing registry connectivity..."
          curl -sv http://host.containers.internal:4000/v2/ || true

          echo "Testing registry connectivity with direct IP..."
          curl -sv http://10.90.0.10:3000/v2/ || true

      - name: Login
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.REGISTRY_OWNER }}/${{ matrix.image.name }}
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" \
            | podman --url "${{ env.PODMAN_URL }}" login --tls-verify=false "${{ env.REGISTRY }}" \
                -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Build
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.REGISTRY_OWNER }}/${{ matrix.image.name }}
        run: |
          podman --url "${{ env.PODMAN_URL }}" build \
            -f "${{ matrix.image.context }}/${{ matrix.image.dockerfile }}" \
            -t "${IMAGE}:${TAG}" \
            -t "${IMAGE}:latest" \
            "${{ matrix.image.context }}"

      - name: Push
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.REGISTRY_OWNER }}/${{ matrix.image.name }}
        run: |
          podman --url "${{ env.PODMAN_URL }}" push --tls-verify=false --retry=5 --retry-delay=5s "${IMAGE}:${TAG}"
          podman --url "${{ env.PODMAN_URL }}" push --tls-verify=false --retry=5 --retry-delay=5s "${IMAGE}:latest"
